In [3]:
import torch
import numpy as np

In [8]:
a = torch.tensor(np.arange(36).reshape((4, 3, 3)))
a

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]],

        [[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]]])

In [11]:
mask = torch.tensor([[1, 1, 1], [1, 1, 0], [1, 0, 0], [1, 0, 0]])

In [48]:
tmp = a * mask.unsqueeze(-1)
print(tmp[:, :, 0].unsqueeze(-1))
tmp.to(torch.float).mean(-1)

tensor([[[ 0],
         [ 3],
         [ 6]],

        [[ 9],
         [12],
         [ 0]],

        [[18],
         [ 0],
         [ 0]],

        [[27],
         [ 0],
         [ 0]]])


tensor([[ 1.,  4.,  7.],
        [10., 13.,  0.],
        [19.,  0.,  0.],
        [28.,  0.,  0.]])

In [49]:
probs = torch.nn.Softmax(dim=1)(tmp[:, :, 0].unsqueeze(-1).to(torch.float))
probs

tensor([[[2.3556e-03],
         [4.7314e-02],
         [9.5033e-01]],

        [[4.7426e-02],
         [9.5257e-01],
         [5.8528e-06]],

        [[1.0000e+00],
         [1.5230e-08],
         [1.5230e-08]],

        [[1.0000e+00],
         [1.8795e-12],
         [1.8795e-12]]])

In [52]:
print(tmp)
(tmp * probs).sum(axis=1)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [ 0,  0,  0]],

        [[18, 19, 20],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[27, 28, 29],
         [ 0,  0,  0],
         [ 0,  0,  0]]])


tensor([[ 5.8439,  6.8439,  7.8439],
        [11.8577, 12.8576, 13.8576],
        [18.0000, 19.0000, 20.0000],
        [27.0000, 28.0000, 29.0000]])

In [45]:
print(torch.nn.Softmax()(torch.tensor([10, 13, 0]).to(torch.float)))
torch.nn.Softmax()(torch.tensor([11, 14, 0]).to(torch.float))

tensor([4.7426e-02, 9.5257e-01, 2.1531e-06])


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1739: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


tensor([4.7426e-02, 9.5257e-01, 7.9209e-07])

In [31]:
print((tmp * probs.unsqueeze(-1)))
print((tmp * probs.unsqueeze(-1)).sum(axis=1))

tensor([[[0.0000e+00, 2.3556e-03, 4.7113e-03],
         [1.4194e-01, 1.8926e-01, 2.3657e-01],
         [5.7020e+00, 6.6523e+00, 7.6026e+00]],

        [[4.2683e-01, 4.7426e-01, 5.2168e-01],
         [1.1431e+01, 1.2383e+01, 1.3336e+01],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[1.8000e+01, 1.9000e+01, 2.0000e+01],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[2.7000e+01, 2.8000e+01, 2.9000e+01],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])
tensor([[ 5.8439,  6.8439,  7.8439],
        [11.8577, 12.8577, 13.8577],
        [18.0000, 19.0000, 20.0000],
        [27.0000, 28.0000, 29.0000]])
